### ISSUE TITLE
Can't access boundnames

### ISSUE THREAD

**Issue by kmarkovich-intera** [MODFLOW-USGS/modflowapi#14]
At risk of this being a very stupid question for the first issue submitted to the MF6 API github page....

I am trying to build a simple contaminant treatment system with the API using drains as extractors and wells as injectors. For more complex CTS configurations, I would like to apportion the extracted water based on boundnames in the MF6 inputs. The problem is, when trying to get the boundnames, I am encountering this error: 

xmipy.errors.XMIError: BMI exception in: get_value_string (for variable modelname/WEL_0/BOUNDNAME)

I have confirmed this variable exists and is non-zero from inspecting mfsim.lst (with memory_print_option all) and the specific code chunk that is failing at is the following (with the model name redacted for privacy):
```
            # get wel boundary info
            addr = ["BOUNDNAME", "modelname", "wel_0"]
            wbaddr = mf6api.get_var_address(*addr)
            wel_bound = mf6api.get_value(wbaddr)
```

I am wondering if accessing string output is not yet supported, or is this user error, or a bug?

**Comment by jlarsen-usgs** [comment]
@kmarkovich-intera 

We do have support for boundnames with the modflow api. Xmipy was updated recently to handle arrays of strings. Try updating xmipy `pip install -U xmipy` or `pip install -U https://github.com/Deltares/xmipy/archive/refs/heads/develop.zip`, a new release just came out

**Comment by kmarkovich-intera** [comment]
I should have said in my issue that I was using the latest versions of modflowapi, xmi, and bmi. I tried updating them again, and get the same error. Is mf6api.get_value() the right function to use to return the array of strings?

**Comment by langevin-usgs** [comment]
You might need to access BOUNDNAME_CST, which is special string type that is supported by the API.

**Comment by langevin-usgs** [comment]
Strings have been a challenge.  At the moment, we only have API access to a special type of string in MODFLOW.  In the MODFLOW source code, these strings are of type CharacterStringType.  I'm surprised you don't see it in the memory listing.  I think we will ultimately get API support for all strings one way or another, but we're not there yet.  I know AUXNAME can be accessed as AUXNAME_CST, but hopefully there aren't any other strings that are important for your work, at least at the moment.

**Comment by kmarkovich-intera** [comment]
No, just the boundname strings. Thanks so much for the help. And I just ran a quick test on my model and confirmed that "  MEMORY_PRINT_OPTION ALL" in mfsim.nam options prints all sorts of variables but none with "_CST" in them.
