### ISSUE TITLE
Can't get the sim object.

### ISSUE THREAD

**Issue by hjia1005** [MODFLOW-USGS/modflowapi#22]
I am getting this issue with all models.
![image](https://github.com/MODFLOW-USGS/modflowapi/assets/33449394/c1e4195d-33b3-4942-a99c-577cf1205bac)

**Comment by jlarsen-usgs** [comment]
@hjia1005 

I've seen this issue previously and it looks like you might have an older version of xmipy installed. Older versions of xmipy did not have support for reading string based variables. My suggestion is to try updating your xmipy installation from the github development branch:

```
pip install -U https://github.com/Deltares/xmipy/archive/refs/heads/develop.zip
```

**Comment by hjia1005** [comment]
@jlarsen-usgs solved immediately, thank you very much!

I have difficulty running the etmodel used in the modflowapi paper - [https://www.sciencedirect.com/science/article/pii/S1364815221002991]
Every time when I run the following line
`success, h0, et0, ims0 = bmi_model(function="constant", verbose=False)
`
the Kernel crashes. The mfsim.stout reports the following error:

![image](https://github.com/MODFLOW-USGS/modflowapi/assets/33449394/2aae7c64-ffb9-4a1a-8a1c-f9698ab1dc95)

I can run the optimized pumping example properly.

**Comment by jlarsen-usgs** [comment]
Interesting, 

Are you working with an older version of libmf6? I'd try updating that too. You can get the most recent version of the shared library from [https://github.com/MODFLOW-USGS/modflow6-nightly-build/actions/runs/5396722914](https://github.com/MODFLOW-USGS/modflow6-nightly-build/actions/runs/5396722914)

**Comment by hjia1005** [comment]
Great, it works with the nightly build version. Thanks a lot!
