### ISSUE TITLE
Error when using large maxbounds (acces violation?)

### ISSUE THREAD

**Issue by martinveenvlietrhdhv** [MODFLOW-USGS/modflowapi#26]
Hello,

When using a large maxbound on stress period data (for example recharge, maxbound = 50000) an error occurs when loading the ListInput class for viewing (and adjusting) transient data. I'm testing with a simple dataset (recharge on 1 cell only), but have tested it with other datasets as well (I guess maxbound is only used for memory purposes, so the dataset itself shouldn't matter as long as it is smaller than maxbound, but have tested larger sets as well just to be sure). I'm using modflow 6.4.2.

Unfortunately the error is quite vague and almost seems to occur randomly (does not seem to occur for all stress packages or all models, however always occurs with rather large models and higher maxbounds):
Process finished with exit code -1073741819 (0xC0000005)

It seems to be some access violation. I have tried running the model on multiple IDEs, locations and with a clean install (only installing the modflow API and it's dependencies), yet the ListInput remains inaccessible.

However, when I lower the maxbound to, for example, 40000 the modflow API loads just fine and the ListInput class for transient data is accessible.

In all cases the Modflow model itself runs fine (and also loads fine in FloPy, just not in the modflow API). It is even possible to run the models through the API with callback (so there seems nothing wrong with the input), it is just not possible to access the ListInput for recharge in this case.

**Comment by jlarsen-usgs** [comment]
@martinveenvlietrhdhv 

Can you zip up and send me a copy of your test model. I'd like to see if I can re-create the issue and track down where the error is occurring.

**Comment by martinveenvlietrhdhv** [comment]
I've shared a copy of the model through email with Jlarsen

**Comment by jlarsen-usgs** [comment]
@martinveenvlietrhdhv 

I have a copy of the model. Working on it today

**Comment by jlarsen-usgs** [comment]
@martinveenvlietrhdhv 

The issue is fixed. It seemed to be a problem with slicing pointers and setting the data in a single line. Large data sets were failing, but now pass when we slice the pointer first and then set it to the numpy recarray

**Comment by martinveenvlietrhdhv** [comment]
Works nicely now! Thank you for looking into the issue and fixing it!
