### ISSUE TITLE
Accessing outputs at end of each timestep

### ISSUE THREAD

**Issue by robinkeegan** [MODFLOW-USGS/modflowapi#31]
Hi there,

This is probably a very simple question but I haven't been able to work it out from the documentation.

I am trying to obtain fluxes from wells at the end of each timestep to pass to another model and then add back into the main model as recharge after a lag period (e.g., for water treatment). 

I can add fluxes into the model using memory location/pointer:
```
R = mf6.get_value_ptr(mf6.get_var_address('RCH_0/BOUND', 'GWF'))
R[:, :] = np.abs(Q) / 10 # set recharge equal to extracted volume distributed between infiltration areas 
```
But I can't work out how to access the flux being removed by a boundary. Put another way, if I have a well named `WEL_0` with auto flow reduce enabled how can I obtain the flux being removed at each timestep? Or alternately if I had a drain named `DRN_0` how could I access the flux?

Many thanks,

Robin

**Comment by dbrakenhoff** [comment]
Hi @robinkeegan, I don't know the answer to your question, but I do know there is an example using the modflowapi that applies pumped water from well packages to a recharge package. Maybe that can yield some insight? Link [here](https://github.com/jlarsen-usgs/Modflow-API-Ag-Package).

**Comment by robinkeegan** [comment]
Many thanks @dbrakenhoff  and @langevin-usgs. I can confirm that the below code obtains the correct fluxes:
```
q_tag = mf6.get_var_address("SIMVALS", "MYGWFMODEL", "WEL_0")
q = mf6.get_value_ptr(q_tag)
```
